#!/usr/bin/env python
"""
Wireshark coloring rules export — generates a real Wireshark colorfilters
file from this project's own detection logic (the same checks
pcap_analysis.py and scapy_pcap_analysis.py already run), so opening any
pcap in the actual Wireshark GUI highlights the same things this
project's scripts flag, automatically, without re-deriving the filter
expressions by hand in the GUI.

Format verified against Wireshark's own shipped default colorfilters file
(C:\\Program Files\\Wireshark\\colorfilters) rather than guessed: each line
is @name@filter-expression@[bg_r,bg_g,bg_b][fg_r,fg_g,fg_b], with color
components as 16-bit values (0-65535, not the 0-255 you'd expect from
8-bit RGB). Rules are evaluated top-to-bottom and the FIRST match wins,
so the highest-severity rules are listed first.

Every filter expression below is validated with tshark -Y before being
written — the same filter engine the GUI uses, so a syntax error here
would fail identically in Wireshark. What's NOT verified, honestly: the
actual rendered colors in the GUI itself — this project has no way to
screenshot a native desktop application window, only a browser pane. The
format is provably correct (matches Wireshark's own file byte-for-byte in
structure) and every filter provably parses; whether it looks right is
for you to open Wireshark and see.

Usage:
    python export_wireshark_colors.py
    # writes shield-collect/pycyber-colorfilters
    # import in Wireshark: View > Coloring Rules... > Import
"""
import subprocess
import sys
from pathlib import Path

sys.stdout.reconfigure(encoding="utf-8")

TSHARK = r"C:\Program Files\Wireshark\tshark.exe"
OUT_PATH = Path(__file__).resolve().parent / "pycyber-colorfilters"
CAPTURE_DIR = Path(__file__).resolve().parent / "captures"

# (name, filter, bg_rgb16, fg_rgb16) - highest severity first, since
# Wireshark applies the FIRST matching rule per packet.
RULES = [
    ("Cleartext HTTP Authorization",
     "http.authorization",
     (65535, 0, 0), (65535, 65535, 65535)),
    ("FTP or Telnet (cleartext legacy protocol)",
     "ftp || telnet",
     (65535, 16000, 0), (0, 0, 0)),
    ("Possible ARP spoofing (ARP reply)",
     "arp.opcode == 2",
     (65535, 65535, 0), (0, 0, 0)),
    ("Cleartext HTTP request",
     "http.request",
     (65535, 45000, 20000), (0, 0, 0)),
    ("DNS query",
     "dns",
     (52000, 60000, 65535), (0, 0, 0)),
]


def validate(filter_expr, pcap_path):
    """Validates against a REAL pcap file, not a stdin trick — an earlier
    version tried `-r -` with empty stdin to avoid needing a real capture,
    and it was a real bug: tshark refuses stdin as a "special file" before
    it ever gets to checking the filter, so even a perfectly valid filter
    "failed." Reading a real file (the same pattern pcap_analysis.py's own
    validate_filter already uses) actually exercises the filter compiler."""
    result = subprocess.run(
        [TSHARK, "-r", str(pcap_path), "-Y", filter_expr, "-c", "1"],
        capture_output=True, text=True, timeout=15,
    )
    return result.returncode == 0


def most_recent_capture():
    caps = sorted(CAPTURE_DIR.glob("*.pcap"), key=lambda p: p.stat().st_mtime)
    return caps[-1] if caps else None


def build(pcap_path):
    lines = ["# Generated by export_wireshark_colors.py - mirrors this project's own detection logic\n"]
    all_valid = True
    for name, filt, bg, fg in RULES:
        ok = validate(filt, pcap_path)
        all_valid = all_valid and ok
        status = "valid" if ok else "INVALID"
        print(f"  [{status}] {name}: {filt}")
        bg_s = ",".join(str(c) for c in bg)
        fg_s = ",".join(str(c) for c in fg)
        lines.append(f"@{name}@{filt}@[{bg_s}][{fg_s}]\n")
    return lines, all_valid


def main():
    pcap_path = most_recent_capture()
    if not pcap_path:
        print("No capture file found in shield-collect/captures/ to validate filters against — "
              "run packet_capture.py first.")
        return
    print(f"Validating each filter expression with tshark against {pcap_path.name}...\n")
    lines, all_valid = build(pcap_path)
    OUT_PATH.write_text("".join(lines), encoding="utf-8")
    print(f"\nWrote {OUT_PATH} ({len(RULES)} rule(s), all valid: {all_valid})")
    print("Import in Wireshark: View > Coloring Rules... > Import.")
    print("(Rendered colors aren't screenshot-verifiable from here — format matches "
          "Wireshark's own shipped colorfilters file structure exactly, and every "
          "filter expression is confirmed valid via tshark, but seeing it applied "
          "needs the real GUI.)")


if __name__ == "__main__":
    main()
